### ISSUE TITLE
Docs #1

### ISSUE THREAD

**Issue by gootieno** [joshsomthin/Airbnb-clone#1]
Hi Josh! Here are some comments regarding the docs. 

Looks like you have enough things listed down to build a clone with enough MVPs!
Here are some thoughts for your schema though. 

- Your amenities and images (possibly Locations depending on how you want to design this) can be columns on your Homes model. It seems like this might be information on one form sent to the that database schema.

**Comment by joshsomthin** [comment]
I think you're right about putting the location on the home table. I think I still want to keep the amenitites seperate, but connect them onto the home table because I still want to create a hasMany relationship so I can get back multiple amenities for a single home.
